In [1]:
import numpy as np

In [2]:
myarr=np.array([[1,2,3,4,]], np.int64)

In [3]:
myarr

array([[1, 2, 3, 4]], dtype=int64)

In [4]:
myarr[0]

array([1, 2, 3, 4], dtype=int64)

In [12]:
myarr[0,2]

3

# converting from other python structure

In [13]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [14]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
listarray.size

9

In [16]:
listarray.shape

(3, 3)

In [17]:
np.array({1,2,3,4})

array({1, 2, 3, 4}, dtype=object)

# intrinstic numpuy array creation object

In [19]:
zeros=np.zeros((3,4))

In [20]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
zeros.shape

(3, 4)

In [22]:
zeros.dtype

dtype('float64')

In [23]:
rng=np.arange(15)

In [24]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [35]:
lspace=np.linspace(1,5,8)

In [36]:
lspace

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [38]:
emp=np.empty((4,3))

In [39]:
emp

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
emp_like=np.empty_like(lspace)

In [43]:
emp_like

array([1.        , 1.57142857, 2.14285714, 2.71428571, 3.28571429,
       3.85714286, 4.42857143, 5.        ])

In [45]:
ide=np.identity(4)

In [46]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
arr=np.arange(99)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [50]:
arr.reshape(33,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89],
       [90, 91, 92],
       [93, 94, 95],
       [96, 97, 98]])

In [56]:
arrr=arr.ravel()

In [57]:
arrr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [60]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [61]:
ar=np.array(x)

In [62]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
ar.sum(axis=0)

array([12, 15, 18])

In [64]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [65]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [66]:
one=np.array([1,4,2,6,44,8])

In [67]:
one

array([ 1,  4,  2,  6, 44,  8])

In [68]:
one.argmax()

4

In [69]:
one.argmin()

0

In [70]:
one.argsort()

array([0, 2, 1, 3, 5, 4], dtype=int64)